# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, verbose_name='nome')),
                ('carga_horaria', models.IntegerField(verbose_name='carga_horaria')),
                ('teoria', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='teoria')),
                ('pratica', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='teoria')),
                ('ementa', models.TextField(verbose_name='ementa')),
                ('competencias', models.TextField(verbose_name='competencias')),
                ('habilidades', models.TextField(verbose_name='habilidades')),
                ('conteudo', models.TextField(verbose_name='conteudo')),
                ('bibliografia_basica', models.TextField(verbose_name='bibliografia_basica')),
                ('bibliografia_complementar', models.TextField(verbose_name='bibliografia_complementar')),
            ],
        ),
    ]
